version: "3.5"

networks:
    default-network:
        name: default-docker-apps-network
        external: true

services:
    docker-web-server:
        image: docker-web-server:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 32M
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
# web server assets volume
#        volumes:
#            - "./../devAssets:/var/www/html/public/assets"
        networks:
            - default-network
